version: '3.7'

services:
  node:
    image: node:12.22.1
    working_dir: /home/node/app
    volumes: 
      - ./:/home/node/app
    environment:
      - .env
    command: sh -c "npm install && npm start"
